spreadsheet_server: server_main.cpp spreadsheet.cpp DependencyGraph.cpp helpers.cpp message.cpp
	g++ -pthread -std=c++11 -o ./Server_Exec server_main.cpp spreadsheet.cpp DependencyGraph.cpp helpers.cpp message.cpp ../Connection/socket_connections.cpp jsoncpp-master/dist/jsoncpp.cpp
